[package]
name = "axol-hot-runner"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
axolc-core = { version = "0.1.0-moss", path = "../axolc-core" }
clap = { version = "4.6.6", features = ["derive"] }
cranelift-codegen = "0.135.1"
cranelift-frontend = "0.135.1"
cranelift-jit = "0.135.1"
cranelift-module = "0.135.1"
notify = "9.0.0-rc.5"
notify-debouncer-full = "0.8.0-rc.2"
