// Owner: PascalElixir / axolrs (GitHub org)
// File: Token types produced by the Axolotl lexer.

use crate::span::Span;
use serde::{Deserialize, Serialize};

/// A single lexical token kind.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum TokenKind {
    // Literals
    IntLit,
    FloatLit,
    StrLit,
    StrPart,
    InterpOpen,
    InterpClose,
    CharLit,
    RawStrLit,
    BytesLit,

    // Identifiers and keywords
    Ident,
    // Keywords
    KwLet,
    KwVar,
    KwFn,
    KwEnd,
    KwIf,
    KwThen,
    KwElseif,
    KwElse,
    KwWhile,
    KwDo,
    KwRepeat,
    KwUntil,
    KwFor,
    KwIn,
    KwBreak,
    KwContinue,
    KwReturn,
    KwMatch,
    KwCase,
    KwStruct,
    KwEnum,
    KwInterface,
    KwUse,
    KwPub,
    KwConst,
    KwTrue,
    KwFalse,
    KwNull,
    KwAnd,
    KwOr,
    KwNot,
    KwSpawn,
    KwAwait,
    KwAsync,
    KwTry,
    KwCatch,
    KwUnsafe,
    KwMove,
    KwBorrow,
    KwType,
    KwWhere,
    KwAs,
    KwIs,
    KwExtern,
    KwNil,
    KwLoop,

    // Primitive type names (treated as idents but tracked)
    KwInt,
    KwUInt,
    KwFloat,
    KwDouble,
    KwBool,
    KwString,
    KwChar,
    KwByte,
    KwI8,
    KwI16,
    KwI32,
    KwI64,
    KwI128,
    KwU8,
    KwU16,
    KwU32,
    KwU64,
    KwU128,
    KwF32,
    KwF64,
    KwStr,
    KwSelfType,

    // Punctuation
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Comma,
    Semicolon,
    Colon,
    DoubleColon,
    Dot,
    DotDot,
    DotDotDot,
    Arrow,
    FatArrow,
    Pipe,
    PipeForward,
    BackPipe,
    Question,
    DoubleQuestion,
    Bang,
    DoubleBang,
    QuestionDot,
    At,
    Hash,
    Dollar,
    Ampersand,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Caret,
    Tilde,
    ShiftLeft,
    ShiftRight,
    Equal,
    DoubleEqual,
    NotEqual,
    LuaNotEqual,
    LessEqual,
    GreaterEqual,
    Less,
    Greater,
    PlusEqual,
    MinusEqual,
    StarEqual,
    SlashEqual,
    PercentEqual,
    AmpersandEqual,
    PipeEqual,
    CaretEqual,
    ShiftLeftEqual,
    ShiftRightEqual,

    // Special
    DocComment,
    Eof,
}

impl TokenKind {
    /// Return a human-readable name for use in diagnostics.
    pub fn describe(self) -> &'static str {
        match self {
            TokenKind::IntLit => "integer literal",
            TokenKind::FloatLit => "float literal",
            TokenKind::StrLit => "string literal",
            TokenKind::StrPart => "string chunk",
            TokenKind::InterpOpen => "interpolation start",
            TokenKind::InterpClose => "interpolation end",
            TokenKind::CharLit => "char literal",
            TokenKind::RawStrLit => "raw string literal",
            TokenKind::BytesLit => "bytes literal",
            TokenKind::Ident => "identifier",
            TokenKind::KwLet => "`let`",
            TokenKind::KwVar => "`var`",
            TokenKind::KwFn => "`fn`",
            TokenKind::KwEnd => "`end`",
            TokenKind::KwIf => "`if`",
            TokenKind::KwThen => "`then`",
            TokenKind::KwElseif => "`elseif`",
            TokenKind::KwElse => "`else`",
            TokenKind::KwWhile => "`while`",
            TokenKind::KwDo => "`do`",
            TokenKind::KwRepeat => "`repeat`",
            TokenKind::KwUntil => "`until`",
            TokenKind::KwFor => "`for`",
            TokenKind::KwIn => "`in`",
            TokenKind::KwBreak => "`break`",
            TokenKind::KwContinue => "`continue`",
            TokenKind::KwReturn => "`return`",
            TokenKind::KwMatch => "`match`",
            TokenKind::KwCase => "`case`",
            TokenKind::KwStruct => "`struct`",
            TokenKind::KwEnum => "`enum`",
            TokenKind::KwInterface => "`interface`",
            TokenKind::KwUse => "`use`",
            TokenKind::KwPub => "`pub`",
            TokenKind::KwConst => "`const`",
            TokenKind::KwTrue => "`true`",
            TokenKind::KwFalse => "`false`",
            TokenKind::KwNull => "`null`",
            TokenKind::KwAnd => "`and`",
            TokenKind::KwOr => "`or`",
            TokenKind::KwNot => "`not`",
            TokenKind::KwSpawn => "`spawn`",
            TokenKind::KwAwait => "`await`",
            TokenKind::KwAsync => "`async`",
            TokenKind::KwTry => "`try`",
            TokenKind::KwCatch => "`catch`",
            TokenKind::KwUnsafe => "`unsafe`",
            TokenKind::KwMove => "`move`",
            TokenKind::KwBorrow => "`borrow`",
            TokenKind::KwType => "`type`",
            TokenKind::KwWhere => "`where`",
            TokenKind::KwAs => "`as`",
            TokenKind::KwIs => "`is`",
            TokenKind::KwExtern => "`extern`",
            TokenKind::KwNil => "`nil`",
            TokenKind::KwLoop => "`loop`",
            TokenKind::KwInt => "`Int`",
            TokenKind::KwUInt => "`UInt`",
            TokenKind::KwFloat => "`Float`",
            TokenKind::KwDouble => "`Double`",
            TokenKind::KwBool => "`Bool`",
            TokenKind::KwString => "`String`",
            TokenKind::KwChar => "`Char`",
            TokenKind::KwByte => "`Byte`",
            TokenKind::KwI8 => "`I8`",
            TokenKind::KwI16 => "`I16`",
            TokenKind::KwI32 => "`I32`",
            TokenKind::KwI64 => "`I64`",
            TokenKind::KwI128 => "`I128`",
            TokenKind::KwU8 => "`U8`",
            TokenKind::KwU16 => "`U16`",
            TokenKind::KwU32 => "`U32`",
            TokenKind::KwU64 => "`U64`",
            TokenKind::KwU128 => "`U128`",
            TokenKind::KwF32 => "`F32`",
            TokenKind::KwF64 => "`F64`",
            TokenKind::KwStr => "`&str`",
            TokenKind::KwSelfType => "`Self`",
            TokenKind::LParen => "`(`",
            TokenKind::RParen => "`)`",
            TokenKind::LBrace => "`{`",
            TokenKind::RBrace => "`}`",
            TokenKind::LBracket => "`[`",
            TokenKind::RBracket => "`]`",
            TokenKind::Comma => "`,`",
            TokenKind::Semicolon => "`;`",
            TokenKind::Colon => "`:`",
            TokenKind::DoubleColon => "`::`",
            TokenKind::Dot => "`.`",
            TokenKind::DotDot => "`..`",
            TokenKind::DotDotDot => "`...`",
            TokenKind::Arrow => "`->`",
            TokenKind::FatArrow => "`=>`",
            TokenKind::Pipe => "`|`",
            TokenKind::PipeForward => "`|>`",
            TokenKind::BackPipe => "`<|`",
            TokenKind::Question => "`?`",
            TokenKind::DoubleQuestion => "`??`",
            TokenKind::Bang => "`!`",
            TokenKind::DoubleBang => "`!!`",
            TokenKind::QuestionDot => "`?.`",
            TokenKind::At => "`@`",
            TokenKind::Hash => "`#`",
            TokenKind::Dollar => "`$`",
            TokenKind::Ampersand => "`&`",
            TokenKind::Plus => "`+`",
            TokenKind::Minus => "`-`",
            TokenKind::Star => "`*`",
            TokenKind::Slash => "`/`",
            TokenKind::Percent => "`%`",
            TokenKind::Caret => "`^`",
            TokenKind::Tilde => "`~`",
            TokenKind::ShiftLeft => "`<<`",
            TokenKind::ShiftRight => "`>>`",
            TokenKind::Equal => "`=`",
            TokenKind::DoubleEqual => "`==`",
            TokenKind::NotEqual => "`!=`",
            TokenKind::LuaNotEqual => "`~=`",
            TokenKind::LessEqual => "`<=`",
            TokenKind::GreaterEqual => "`>=`",
            TokenKind::Less => "`<`",
            TokenKind::Greater => "`>`",
            TokenKind::PlusEqual => "`+=`",
            TokenKind::MinusEqual => "`-=`",
            TokenKind::StarEqual => "`*=`",
            TokenKind::SlashEqual => "`/=`",
            TokenKind::PercentEqual => "`%=`",
            TokenKind::AmpersandEqual => "`&=`",
            TokenKind::PipeEqual => "`|=`",
            TokenKind::CaretEqual => "`^=`",
            TokenKind::ShiftLeftEqual => "`<<=`",
            TokenKind::ShiftRightEqual => "`>>=`",
            TokenKind::DocComment => "doc comment",
            TokenKind::Eof => "end of file",
        }
    }
}

/// A token with its span and source text.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
    pub text: String,
}
