// Owner: PascalElixir / axolrs (GitHub org)
// File: Rust code generation - emits idiomatic Rust from a lowered Axolotl HIR module.

use crate::ast::*;
use crate::ffi;
use crate::hir::{ImplBlock, Item as HirItem, Module as HirModule};
use std::collections::HashMap;

/// The Rust code generator.
pub struct Codegen {
    out: String,
    indent: usize,
    /// Names of declared types (structs/enums), used to emit `Type::method()` static calls.
    type_names: Vec<String>,
    /// Struct field types (type name -> field name -> Rust type text).
    struct_fields: HashMap<String, HashMap<String, String>>,
    /// Which (type, method) pairs write through `self`.
    method_write_table: HashMap<(String, String), bool>,
    /// Inferred mutable names for the function currently being emitted.
    current_muts: Option<Vec<String>>,
    /// Top-level function names whose return type is a function type.
    fn_returns_fn: std::collections::HashSet<String>,
    /// Inferred var kinds (name -> "Vec"/"Map"/struct name) for the fn being emitted.
    current_var_kinds: Option<HashMap<String, String>>,
    /// Top-level Int const names usable as count-loop bounds (`for i in N`).
    int_consts: std::collections::HashSet<String>,
}

impl Codegen {
    /// Construct a fresh code generator.
    pub fn new() -> Codegen {
        Codegen {
            out: String::new(),
            indent: 0,
            type_names: Vec::new(),
            struct_fields: HashMap::new(),
            method_write_table: HashMap::new(),
            current_muts: None,
            fn_returns_fn: std::collections::HashSet::new(),
            current_var_kinds: None,
            int_consts: std::collections::HashSet::new(),
        }
    }

    /// Generate a complete Rust module from a lowered HIR module.
    pub fn emit_module(&mut self, module: &HirModule) -> String {
        for item in &module.items {
            if let HirItem::Const(c) = item {
                if int_const_value(&c.value) {
                    self.int_consts.insert(c.name.name.clone());
                }
            }
        }
        for item in &module.items {
            match item {
                HirItem::Struct(s) => {
                    self.type_names.push(s.name.name.clone());
                    let mut fields = HashMap::new();
                    for f in &s.fields {
                        fields.insert(f.name.name.clone(), crate::types::from_annot(&f.ty).to_rust());
                    }
                    self.struct_fields.insert(s.name.name.clone(), fields);
                }
                HirItem::Enum(e) => self.type_names.push(e.name.name.clone()),
                HirItem::Impl(imp) => {
                    for m in &imp.methods {
                        if is_fn_type(&m.ret) {
                            self.fn_returns_fn.insert(m.name.name.clone());
                        }
                        self.method_write_table.insert(
                            (imp.ty_name.name.clone(), m.name.name.clone()),
                            crate::ownership::method_writes_self(&m.body),
                        );
                    }
                    for m in &imp.static_methods {
                        if is_fn_type(&m.ret) {
                            self.fn_returns_fn.insert(m.name.name.clone());
                        }
                        self.method_write_table.insert(
                            (imp.ty_name.name.clone(), m.name.name.clone()),
                            false,
                        );
                    }
                }
                HirItem::Fn(f) => {
                    if is_fn_type(&f.ret) {
                        self.fn_returns_fn.insert(f.name.name.clone());
                    }
                }
                _ => {}
            }
        }
        self.emit("// Generated by axolc - do not edit by hand.\n");
        self.emit("// Owner: PascalElixir / axolrs (GitHub org)\n\n");
        for item in &module.items {
            self.emit_item(item);
        }
        self.out.clone()
    }

    fn emit(&mut self, s: &str) {
        self.out.push_str(s);
    }

    fn newline(&mut self) {
        self.out.push('\n');
    }

    fn indent(&mut self) {
        for _ in 0..self.indent { self.out.push_str("    "); }
    }

    fn emit_item(&mut self, item: &HirItem) {
        match item {
            HirItem::Use(u) => {
                self.emit("use ");
                self.emit(&u.path);
                self.emit(";\n");
            }
            HirItem::Fn(f) => self.emit_fn(f),
            HirItem::Struct(s) => self.emit_struct(s),
            HirItem::Enum(e) => self.emit_enum(e),
            HirItem::Interface(i) => self.emit_interface(i),
            HirItem::Const(c) => self.emit_const(c),
            HirItem::TypeAlias(t) => self.emit_type_alias(t),
            HirItem::Impl(i) => self.emit_impl_block(i),
            HirItem::ExternBlock(e) => {
                self.emit("extern \"");
                self.emit(&e.abi);
                self.emit("\" { }\n");
            }
            HirItem::Foreign(b) => self.emit_foreign(b),
            HirItem::ModuleDoc(text, _) => {
                if !text.is_empty() {
                    self.emit("// ");
                    self.emit(text);
                    self.newline();
                }
            }
        }
    }

    /// Emit one grouped impl block with all its instance and static methods.
    fn emit_impl_block(&mut self, i: &ImplBlock) {
        self.emit("impl ");
        if let Some(intf) = &i.interface_name {
            self.emit(&intf.name);
            self.emit(" for ");
        }
        self.emit(&i.ty_name.name);
        self.emit(" {\n");
        self.indent += 1;
        for m in &i.methods {
            self.emit_impl_method(m, true);
        }
        for m in &i.static_methods {
            self.emit_impl_method(m, false);
        }
        self.indent -= 1;
        self.emit("}\n\n");
    }

    /// Emit one method inside an impl block; `with_self` controls the receiver parameter.
    fn emit_impl_method(&mut self, m: &MethodItem, with_self: bool) {
        self.indent();
        if m.is_async {
            self.emit("async ");
        }
        self.emit("fn ");
        self.emit(&m.name.name);
        self.emit("(");
        let (muts, kinds) = analyze_mutability(&m.body, &self.method_write_table, &self.fn_returns_fn);
        self.current_muts = Some(muts);
        self.current_var_kinds = Some(kinds);
        let mut first = true;
        if with_self {
            let writes_self = crate::ownership::method_writes_self(&m.body);
            let borrows_self = m.params.first().is_some_and(|p| p.name.name == "self");
            if borrows_self {
                if writes_self { self.emit("&mut self"); } else { self.emit("&self"); }
            } else {
                self.emit("self");
            }
            first = false;
        }
        let skip = if with_self && m.params.first().is_some_and(|p| p.name.name == "self") {
            1
        } else {
            0
        };
        for p in m.params.iter().skip(skip) {
            if !first {
                self.emit(", ");
            }
            if is_fn_type(&p.ty)
                || self.current_muts.as_ref().is_some_and(|m| m.contains(&p.name.name)) {
                self.emit("mut ");
            }
            self.emit(&p.name.name);
            if let Some(t) = &p.ty {
                self.emit(": ");
                self.emit_type(t);
            }
            first = false;
        }
        self.emit(")");
        if let Some(r) = &m.ret {
            self.emit(" -> ");
            self.emit_type(r);
        }
        self.emit(" ");
        self.emit_block(&m.body);
        self.current_muts = None;
        self.current_var_kinds = None;
        self.newline();
    }

    /// Emit a foreign block: rblock passes through verbatim, cblock/cppblock become extern declarations,
    /// pyblock becomes a feature-gated Python bridge module.
    fn emit_foreign(&mut self, b: &ForeignBlock) {
        match b.kind {
            ForeignKind::Rust => {
                let body = b.body.trim();
                if !body.is_empty() {
                    self.emit(body);
                    if !body.ends_with('\n') {
                        self.newline();
                    }
                    self.newline();
                }
            }
            ForeignKind::C | ForeignKind::Cpp => {
                let fns = ffi::extract_c_functions(&b.body);
                if fns.is_empty() {
                    return;
                }
                self.emit("extern \"C\" {\n");
                self.indent += 1;
                for f in &fns {
                    self.indent();
                    if b.kind == ForeignKind::Cpp {
                        let mangled = ffi::cpp_mangle(&f.name, &f.params);
                        self.emit(&format!("#[link_name = \"{}\"]\n", mangled));
                        self.indent();
                    }
                    let params = f
                        .params
                        .iter()
                        .map(|(n, t)| format!("{}: {}", n, t))
                        .collect::<Vec<_>>()
                        .join(", ");
                    self.emit(&format!("fn {}({});\n", f.name, params));
                }
                self.indent -= 1;
                self.emit("}\n\n");
            }
            ForeignKind::Python => {
                let body = b.body.trim();
                if body.is_empty() {
                    return;
                }
                self.emit("#[cfg(feature = \"axol-python\")]\n");
                self.emit("mod axol_python {\n");
                self.indent += 1;
                self.indent();
                self.emit("pub const PYTHON_SOURCE: &str = r####\"");
                self.emit(body);
                self.emit("\"####;\n");
                self.indent -= 1;
                self.emit("}\n\n");
            }
        }
    }

    fn emit_fn(&mut self, f: &FnItem) {
        if f.is_pub { self.emit("pub "); }
        if f.is_async { self.emit("async "); }
        if f.is_extern { self.emit("extern "); }
        self.emit("fn ");
        self.emit(&f.name.name);
        self.emit_generic_params(&f.generics);
        self.emit("(");
        let (muts, kinds) = analyze_mutability(&f.body, &self.method_write_table, &self.fn_returns_fn);
        self.current_muts = Some(muts);
        self.current_var_kinds = Some(kinds);
        for (i, p) in f.params.iter().enumerate() {
            if i > 0 { self.emit(", "); }
            if is_fn_type(&p.ty)
                || self.current_muts.as_ref().is_some_and(|m| m.contains(&p.name.name)) {
                self.emit("mut ");
            }
            self.emit(&p.name.name);
            if let Some(ty) = &p.ty {
                self.emit(": ");
                self.emit_type(ty);
            }
        }
        self.emit(")");
        if let Some(ret) = &f.ret {
            self.emit(" -> ");
            self.emit_type(ret);
        }
        if f.is_extern {
            self.emit(";\n");
        } else {
            self.emit(" ");
            self.emit_block(&f.body);
            self.newline();
        }
        self.current_muts = None;
        self.current_var_kinds = None;
    }

    /// True when a print argument needs `{:?}` formatting (collections have no Display).
    fn arg_needs_debug(&self, a: &CallArg) -> bool {
        if let Some(e) = call_arg_expr(a) {
            match e {
                Expr::Array(..) | Expr::Map(..) | Expr::Tuple(..) => return true,
                Expr::Ident(id) => {
                    if let Some(kinds) = &self.current_var_kinds {
                        return matches!(kinds.get(&id.name).map(|s| s.as_str()), Some("Vec") | Some("Map"));
                    }
                }
                _ => {}
            }
        }
        false
    }

    fn emit_struct(&mut self, s: &StructItem) {
        if s.is_pub { self.emit("pub "); }
        self.emit("struct ");
        self.emit(&s.name.name);
        self.emit_generic_params(&s.generics);
        if s.fields.is_empty() {
            self.emit(";\n");
            return;
        }
        self.emit(" {\n");
        self.indent += 1;
        for field in &s.fields {
            self.indent();
            if field.is_pub { self.emit("pub "); }
            self.emit(&field.name.name);
            self.emit(": ");
            self.emit_type(&field.ty);
            self.emit(",\n");
        }
        self.indent -= 1;
        self.emit("}\n");
    }

    fn emit_enum(&mut self, e: &EnumItem) {
        if e.is_pub { self.emit("pub "); }
        self.emit("enum ");
        self.emit(&e.name.name);
        self.emit_generic_params(&e.generics);
        self.emit(" {\n");
        self.indent += 1;
        for v in &e.variants {
            self.indent();
            self.emit(&v.name.name);
            if v.fields.is_empty() {
                self.emit(",\n");
                continue;
            }
            // Tuple-style variant
            if v.fields.iter().all(|f| f.name.is_none()) {
                self.emit("(");
                for (i, f) in v.fields.iter().enumerate() {
                    if i > 0 { self.emit(", "); }
                    self.emit_type(&f.ty);
                }
                self.emit("),\n");
            } else {
                self.emit(" {\n");
                self.indent += 1;
                for f in &v.fields {
                    self.indent();
                    if let Some(n) = &f.name {
                        self.emit(&n.name);
                        self.emit(": ");
                    }
                    self.emit_type(&f.ty);
                    self.emit(",\n");
                }
                self.indent -= 1;
                self.indent();
                self.emit("},\n");
            }
        }
        self.indent -= 1;
        self.emit("}\n");
    }

    fn emit_interface(&mut self, i: &InterfaceItem) {
        if i.is_pub { self.emit("pub "); }
        self.emit("trait ");
        self.emit(&i.name.name);
        self.emit_generic_params(&i.generics);
        self.emit(" {\n");
        self.indent += 1;
        for m in &i.methods {
            self.indent();
            self.emit("fn ");
            self.emit(&m.name.name);
            self.emit("(");
            for (i, p) in m.params.iter().enumerate() {
                if i > 0 { self.emit(", "); }
                self.emit(&p.name.name);
                if let Some(t) = &p.ty {
                    self.emit(": ");
                    self.emit_type(t);
                }
            }
            self.emit(")");
            if let Some(r) = &m.ret {
                self.emit(" -> ");
                self.emit_type(r);
            }
            if let Some(body) = &m.default_body {
                self.emit(" { ");
                self.emit_block_inline(body);
                self.emit(" }\n");
            } else {
                self.emit(";\n");
            }
        }
        self.indent -= 1;
        self.emit("}\n");
    }

    fn emit_const(&mut self, c: &ConstItem) {
        if c.is_pub { self.emit("pub "); }
        self.emit("const ");
        self.emit(&c.name.name);
        if let Some(ty) = &c.ty {
            self.emit(": ");
            self.emit_type(ty);
        } else {
            self.emit(": _");
        }
        self.emit(" = ");
        self.emit_expr(&c.value);
        self.emit(";\n");
    }

    fn emit_type_alias(&mut self, t: &TypeAliasItem) {
        if t.is_pub { self.emit("pub "); }
        self.emit("type ");
        self.emit(&t.name.name);
        self.emit_generic_params(&t.generics);
        self.emit(" = ");
        self.emit_type(&t.ty);
        self.emit(";\n");
    }

    fn emit_generic_params(&mut self, generics: &[Ident]) {
        if generics.is_empty() { return; }
        self.emit("<");
        for (i, g) in generics.iter().enumerate() {
            if i > 0 { self.emit(", "); }
            self.emit(&g.name);
        }
        self.emit(">");
    }

    fn emit_type(&mut self, ty: &TypeAnnot) {
        let t = crate::types::from_annot(ty);
        self.emit(&t.to_rust());
    }

    /// True when the analysis pass recorded this binding as Int (i64 semantics
    /// for a bare integer literal initializer, matching the interpreter).
    fn is_inferred_int(&self, name: &str) -> bool {
        self.current_var_kinds
            .as_ref()
            .is_some_and(|k| k.get(name).map(|s| s.as_str()) == Some("Int"))
    }

    fn emit_block(&mut self, block: &Block) {
        self.emit("{\n");
        self.indent += 1;
        for s in &block.stmts {
            self.emit_stmt(s);
        }
        if let Some(tail) = &block.tail {
            self.indent();
            self.emit_expr(tail);
            self.emit("\n");
        }
        self.indent -= 1;
        self.indent();
        self.emit("}");
    }

    fn emit_block_inline(&mut self, block: &Block) {
        self.emit("{ ");
        for s in &block.stmts {
            self.emit_stmt_inline(s);
        }
        if let Some(tail) = &block.tail {
            self.emit_expr(tail);
        }
        self.emit(" }");
    }

    fn emit_stmt(&mut self, s: &Stmt) {
        self.indent();
        match s {
            Stmt::Let { name, ty, value, .. } => {
                let needs_mut = self
                    .current_muts
                    .as_ref()
                    .is_some_and(|m| m.contains(&name.name));
                if needs_mut { self.emit("let mut "); } else { self.emit("let "); }
                self.emit(&name.name);
                if let Some(t) = ty {
                    self.emit(": ");
                    self.emit_type(t);
                } else if self.is_inferred_int(&name.name) {
                    self.emit(": i64");
                }
                self.emit(" = ");
                self.emit_expr(value);
                self.emit(";\n");
            }
            Stmt::Var { name, ty, value, .. } => {
                self.emit("let mut ");
                self.emit(&name.name);
                if let Some(t) = ty {
                    self.emit(": ");
                    self.emit_type(t);
                } else if self.is_inferred_int(&name.name) {
                    self.emit(": i64");
                }
                self.emit(" = ");
                self.emit_expr(value);
                self.emit(";\n");
            }
            Stmt::Assign { target, value, op, .. } => {
                self.emit_expr(target);
                self.emit_op(*op);
                self.emit_expr(value);
                self.emit(";\n");
            }
            Stmt::Expr(e, _) => {
                self.emit_expr(e);
                self.emit(";\n");
            }
            Stmt::If { cond, then_body, elseifs, else_body, .. } => {
                self.emit("if ");
                self.emit_expr(cond);
                self.emit(" ");
                self.emit_block(then_body);
                for (c, b) in elseifs {
                    self.emit(" else if ");
                    self.emit_expr(c);
                    self.emit(" ");
                    self.emit_block(b);
                }
                if let Some(b) = else_body {
                    self.emit(" else ");
                    self.emit_block(b);
                }
                self.emit("\n");
            }
            Stmt::While { cond, body, .. } => {
                self.emit("while ");
                self.emit_expr(cond);
                self.emit(" ");
                self.emit_block(body);
                self.emit("\n");
            }
            Stmt::Repeat { body, cond, .. } => {
                self.emit("loop ");
                let mut combined = body.clone();
                let cspan = cond.span();
                combined.stmts.push(Stmt::If {
                    cond: (*cond).clone(),
                    then_body: Block {
                        stmts: vec![Stmt::Break(cspan)],
                        tail: None,
                        span: cspan,
                    },
                    elseifs: Vec::new(),
                    else_body: None,
                    span: cspan,
                });
                self.emit_block(&combined);
                self.emit("\n");
            }
            Stmt::For { var, iter, body, .. } => {
                self.emit("for ");
                self.emit(&var.name);
                self.emit(" in ");
                let const_count = matches!(
                    iter,
                    Expr::Ident(id) if self.int_consts.contains(&id.name)
                );
                if const_count {
                    self.emit("0..");
                }
                self.emit_expr(iter);
                self.emit(" ");
                self.emit_block(body);
                self.emit("\n");
            }
            Stmt::Loop { body, .. } => {
                self.emit("loop ");
                self.emit_block(body);
                self.emit("\n");
            }
            Stmt::Break(_) => self.emit("break;\n"),
            Stmt::Continue(_) => self.emit("continue;\n"),
            Stmt::Return(e, _) => {
                self.emit("return");
                if let Some(e) = e {
                    self.emit(" ");
                    self.emit_expr(e);
                }
                self.emit(";\n");
            }
            Stmt::Match { scrutinee, arms, .. } => {
                self.emit("match ");
                self.emit_expr(scrutinee);
                self.emit(" {\n");
                self.indent += 1;
                for arm in arms {
                    self.indent();
                    self.emit_pattern(&arm.pattern);
                    if let Some(g) = &arm.guard {
                        self.emit(" if ");
                        self.emit_expr(g);
                    }
                    self.emit(" => ");
                    self.emit_block(&arm.body);
                    self.emit(",\n");
                }
                self.indent -= 1;
                self.indent();
                self.emit("}\n");
            }
            Stmt::Block(b, _) => {
                self.emit_block(b);
                self.emit("\n");
            }
            Stmt::Unsafe(b, _) => {
                self.emit("unsafe ");
                self.emit_block(b);
                self.emit("\n");
            }
            Stmt::Spawn { call, .. } => {
                self.emit("tokio::spawn(async move ");
                self.emit_expr(call);
                self.emit(");\n");
            }
        }
    }

    fn emit_stmt_inline(&mut self, s: &Stmt) {
        match s {
            Stmt::Let { name, ty, value, .. } => {
                self.emit(&format!("let {} {}= ", name.name, if let Some(t)=ty { format!(": {}", crate::types::from_annot(t).to_rust()) } else { String::new() }));
                self.emit_expr(value);
                self.emit("; ");
            }
            Stmt::Expr(e, _) => {
                self.emit_expr(e);
                self.emit("; ");
            }
            _ => self.emit("/* stmt */ "),
        }
    }

    fn emit_op(&mut self, op: AssignOp) {
        match op {
            AssignOp::Assign => self.emit(" = "),
            AssignOp::Add => self.emit(" += "),
            AssignOp::Sub => self.emit(" -= "),
            AssignOp::Mul => self.emit(" *= "),
            AssignOp::Div => self.emit(" /= "),
            AssignOp::Rem => self.emit(" %= "),
            AssignOp::And => self.emit(" &= "),
            AssignOp::Or => self.emit(" |= "),
            AssignOp::Xor => self.emit(" ^= "),
            AssignOp::Shl => self.emit(" <<= "),
            AssignOp::Shr => self.emit(" >>= "),
        }
    }

    fn emit_pattern(&mut self, p: &Pattern) {
        match p {
            Pattern::Wild(_) => self.emit("_"),
            Pattern::Lit(e, _) => self.emit_expr(e),
            Pattern::Binding(id) => self.emit(&id.name),
            Pattern::EnumVariant { ty, variant, sub, .. } => {
                self.emit(&ty.name);
                self.emit("::");
                self.emit(&variant.name);
                if !sub.is_empty() {
                    self.emit("(");
                    for (i, s) in sub.iter().enumerate() {
                        if i > 0 { self.emit(", "); }
                        self.emit_pattern(s);
                    }
                    self.emit(")");
                }
            }
            Pattern::Struct { ty, fields, .. } => {
                self.emit(&ty.name);
                if fields.is_empty() {
                    self.emit(" {..}");
                } else {
                    self.emit(" { ");
                    for (i, (n, p)) in fields.iter().enumerate() {
                        if i > 0 { self.emit(", "); }
                        self.emit(&n.name);
                        if !matches!(p, Pattern::Binding(_)) {
                            self.emit(": ");
                            self.emit_pattern(p);
                        }
                    }
                    self.emit(" }");
                }
            }
            Pattern::Tuple(elems, _) => {
                self.emit("(");
                for (i, p) in elems.iter().enumerate() {
                    if i > 0 { self.emit(", "); }
                    self.emit_pattern(p);
                }
                self.emit(")");
            }
            Pattern::Array(elems, _) => {
                self.emit("[");
                for (i, p) in elems.iter().enumerate() {
                    if i > 0 { self.emit(", "); }
                    self.emit_pattern(p);
                }
                self.emit("]");
            }
            Pattern::Or(alts, _) => {
                for (i, p) in alts.iter().enumerate() {
                    if i > 0 { self.emit(" | "); }
                    self.emit_pattern(p);
                }
            }
            Pattern::As(inner, name, _) => {
                self.emit_pattern(inner);
                self.emit(" @ ");
                self.emit(&name.name);
            }
        }
    }

    fn emit_expr(&mut self, e: &Expr) {
        match e {
            Expr::IntLit(s, _) => self.emit(s),
            Expr::FloatLit(s, _) => self.emit(s),
            Expr::StrLit(s, _) => {
                self.emit("\"");
                for c in s.chars() {
                    match c {
                        '"' => self.emit("\\\""),
                        '\\' => self.emit("\\\\"),
                        '\n' => self.emit("\\n"),
                        '\r' => self.emit("\\r"),
                        '\t' => self.emit("\\t"),
                        _ => self.push_char(c),
                    }
                }
                self.emit("\"");
            }
            Expr::CharLit(s, _) => {
                self.emit("'");
                for c in s.chars() {
                    match c {
                        '\'' => self.emit("\\'"),
                        '\\' => self.emit("\\\\"),
                        '\n' => self.emit("\\n"),
                        '\r' => self.emit("\\r"),
                        '\t' => self.emit("\\t"),
                        _ => self.push_char(c),
                    }
                }
                self.emit("'");
            }
            Expr::RawStrLit(s, _) => {
                self.emit("r\"");
                self.emit(s);
                self.emit("\"");
            }
            Expr::BoolLit(b, _) => self.emit(if *b { "true" } else { "false" }),
            Expr::Null(_) => self.emit("None"),
            Expr::Ident(id) => self.emit(&id.name),
            Expr::SelfExpr(_) => self.emit("self"),
            Expr::InterpStr(parts, _) => {
                self.emit("format!(\"");
                for p in parts {
                    match p {
                        InterpStrPart::Text(t) => {
                            for c in t.chars() {
                                match c {
                                    '"' => self.emit("\\\""),
                                    '\\' => self.emit("\\\\"),
                                    '\n' => self.emit("\\n"),
                                    '\r' => self.emit("\\r"),
                                    '\t' => self.emit("\\t"),
                                    _ => self.push_char(c),
                                }
                            }
                        }
                        InterpStrPart::Expr(_) => {
                            self.emit("{}");
                        }
                    }
                }
                self.emit("\"");
                for p in parts {
                    if let InterpStrPart::Expr(e) = p {
                        self.emit(", ");
                        self.emit_expr(e);
                    }
                }
                self.emit(")");
            }
            Expr::Array(elems, _) => {
                self.emit("vec![");
                for (i, e) in elems.iter().enumerate() {
                    if i > 0 { self.emit(", "); }
                    self.emit_expr(e);
                }
                self.emit("]");
            }
            Expr::Map(fields, _) => {
                self.emit("{ let mut __m = std::collections::HashMap::new(); ");
                for f in fields {
                    self.emit("__m.insert(");
                    self.emit_expr(&f.key);
                    self.emit(", ");
                    self.emit_expr(&f.value);
                    self.emit("); ");
                }
                self.emit("__m }");
            }
            Expr::StructLit(ty, fields, _) => {
                self.emit(&ty.name);
                if fields.is_empty() {
                    self.emit("::default()");
                } else {
                    self.emit(" { ");
                    for (i, f) in fields.iter().enumerate() {
                        if i > 0 { self.emit(", "); }
                        let fname = match &f.key {
                            Expr::Ident(n) => n.name.clone(),
                            _ => String::new(),
                        };
                        self.emit(&fname);
                        self.emit(": ");
                        let field_is_string = self
                            .struct_fields
                            .get(&ty.name)
                            .and_then(|m| m.get(&fname))
                            .is_some_and(|t| t == "String");
                        if field_is_string {
                            if let Expr::StrLit(s, sspan) = &f.value {
                                let lit = Expr::StrLit(s.clone(), *sspan);
                                self.emit_expr(&lit);
                                self.emit(".to_string()");
                                continue;
                            }
                        }
                        self.emit_expr(&f.value);
                    }
                    self.emit(" }");
                }
            }
            Expr::Tuple(elems, _) => {
                self.emit("(");
                for (i, e) in elems.iter().enumerate() {
                    if i > 0 { self.emit(", "); }
                    self.emit_expr(e);
                }
                if elems.len() == 1 { self.emit(","); }
                self.emit(")");
            }
            Expr::Range(lo, hi, inclusive, _) => {
                if let Some(l) = lo { self.emit_expr(l); } else { self.emit("..") }
                if *inclusive { self.emit("..=") } else {
                    if lo.is_some() { self.emit("..") }
                }
                if let Some(h) = hi { self.emit_expr(h); }
            }
            Expr::BinOp(l, op, r, _) => {
                self.emit_binop_child(l, *op, true);
                self.emit(" ");
                self.emit_binop(*op);
                self.emit(" ");
                self.emit_binop_child(r, *op, false);
            }
            Expr::UnaryOp(op, e, _) => {
                match op {
                    UnaryOp::Neg => self.emit("-("),
                    UnaryOp::Not => self.emit("!("),
                    UnaryOp::BitNot => self.emit("!("),
                    UnaryOp::Ref => self.emit("&("),
                    UnaryOp::MutRef => self.emit("&mut "),
                    UnaryOp::Deref => self.emit("*("),
                }
                self.emit_expr(e);
                if !matches!(op, UnaryOp::MutRef) {
                    self.emit(")");
                }
            }
            Expr::Assign(target, op, val, _) => {
                self.emit_expr(target);
                self.emit_op(*op);
                self.emit_expr(val);
            }
            Expr::Call(callee, args, _) => {
                let macro_name = match callee.as_ref() {
                    Expr::Ident(id) if id.name == "print" || id.name == "println" => {
                        Some(id.name.clone())
                    }
                    _ => None,
                };
                if let Some(_) = macro_name {
                    self.emit("println!(\"");
                    for (i, a) in args.iter().enumerate() {
                        if i > 0 { self.emit(" "); }
                        if self.arg_needs_debug(a) { self.emit("{:?}"); } else { self.emit("{}"); }
                    }
                    self.emit("\", ");
                    self.emit_call_args(args);
                    self.emit(")");
                } else {
                    self.emit_expr(callee);
                    self.emit("(");
                    self.emit_call_args(args);
                    self.emit(")");
                }
            }
            Expr::MethodCall(recv, name, args, _, _) => {
                let static_call = matches!(recv.as_ref(), Expr::Ident(id) if self.type_names.contains(&id.name));
                if static_call {
                    if let Expr::Ident(id) = recv.as_ref() {
                        self.emit(&id.name);
                    }
                    self.emit("::");
                } else {
                    self.emit_expr(recv);
                    self.emit(".");
                }
                self.emit(&name.name);
                self.emit("(");
                self.emit_call_args(args);
                self.emit(")");
            }
            Expr::Field(recv, name, _) => {
                self.emit_expr(recv);
                self.emit(".");
                self.emit(&name.name);
            }
            Expr::Index(arr, idx, _) => {
                self.emit_expr(arr);
                self.emit("[");
                self.emit_expr(idx);
                self.emit("]");
            }
            Expr::Closure(params, ret, body, _) => {
                self.emit("Box::new(");
                if closure_captures(params, body) {
                    self.emit("move ");
                }
                self.emit("|");
                for (i, p) in params.iter().enumerate() {
                    if i > 0 { self.emit(", "); }
                    self.emit(&p.name.name);
                    if let Some(t) = &p.ty {
                        self.emit(": ");
                        self.emit_type(t);
                    }
                }
                self.emit("|");
                if let Some(r) = ret {
                    self.emit(" -> ");
                    self.emit_type(r);
                }
                self.emit(" ");
                self.emit_block(body);
                self.emit(")");
            }
            Expr::IfExpr(cond, then_body, elseifs, else_body, _) => {
                self.emit("(if ");
                self.emit_expr(cond);
                self.emit(" ");
                self.emit_block(then_body);
                for (c, b) in elseifs {
                    self.emit(" else if ");
                    self.emit_expr(c);
                    self.emit(" ");
                    self.emit_block(b);
                }
                if let Some(b) = else_body {
                    self.emit(" else ");
                    self.emit_block(b);
                } else {
                    self.emit(" else { () }");
                }
                self.emit(")");
            }
            Expr::MatchExpr(scrut, arms, _) => {
                self.emit("(match ");
                self.emit_expr(scrut);
                self.emit(" {\n");
                self.indent += 1;
                for arm in arms {
                    self.indent();
                    self.emit_pattern(&arm.pattern);
                    if let Some(g) = &arm.guard {
                        self.emit(" if ");
                        self.emit_expr(g);
                    }
                    self.emit(" => ");
                    self.emit_block(&arm.body);
                    self.emit(",\n");
                }
                self.indent -= 1;
                self.indent();
                self.emit("})");
            }
            Expr::BlockExpr(b, _) => {
                self.emit_block(b);
            }
            Expr::PipeForward(left, right, _) => {
                self.emit("(");
                self.emit_expr(right);
                self.emit("(");
                self.emit_expr(left);
                self.emit("))");
            }
            Expr::BackPipe(right, left, _) => {
                self.emit("(");
                self.emit_expr(right);
                self.emit("(");
                self.emit_expr(left);
                self.emit("))");
            }
            Expr::Await(e, _) => {
                self.emit("(");
                self.emit_expr(e);
                self.emit(".await)");
            }
            Expr::Try(e, _) => {
                self.emit("(");
                self.emit_expr(e);
                self.emit("?)");
            }
            Expr::Bang(e, _) => {
                self.emit("(");
                self.emit_expr(e);
                self.emit(".unwrap())");
            }
            Expr::QuestionDot(recv, field, _) => {
                self.emit_expr(recv);
                self.emit(".map(|x| x.");
                self.emit(&field.name);
                self.emit(")");
            }
            Expr::Cast(e, t, _) => self.emit_cast(e, t),
            Expr::As(e, t, _) => self.emit_cast(e, t),
            Expr::Spread(e, _) => self.emit_expr(e),
            Expr::Unit(_) => self.emit("()"),
        }
    }

    /// Emit a cast, parenthesizing binary operands so `as` cannot capture
    /// only the right operand (`pc + 1 as usize` must parse as `(pc + 1) as usize`).
    fn emit_cast(&mut self, e: &Expr, t: &TypeAnnot) {
        let operand_parens = matches!(e, Expr::BinOp(..) | Expr::Range(..));
        self.emit("(");
        if operand_parens { self.emit("("); }
        self.emit_expr(e);
        if operand_parens { self.emit(")"); }
        self.emit(" as ");
        self.emit_type(t);
        self.emit(")");
    }

    /// Emit a binary operand, parenthesizing only when precedence requires it.
    fn emit_binop_child(&mut self, e: &Expr, parent: BinOp, is_left: bool) {
        let child_prec = match e {
            Expr::BinOp(_, op, _, _) => Some(binop_precedence(*op)),
            Expr::Cast(inner, _, _) | Expr::As(inner, _, _) => {
                if matches!(inner.as_ref(), Expr::BinOp(_, _, _, _)) {
                    Some(0)
                } else {
                    None
                }
            }
            _ => None,
        };
        let parent_prec = binop_precedence(parent);
        let needs_parens = match child_prec {
            Some(cp) => {
                if is_left {
                    cp < parent_prec
                } else {
                    cp <= parent_prec
                }
            }
            None => false,
        };
        if needs_parens {
            self.emit("(");
            self.emit_expr(e);
            self.emit(")");
        } else {
            self.emit_expr(e);
        }
    }

    fn push_char(&mut self, c: char) {
        let mut buf = [0u8; 4];
        self.out.push_str(c.encode_utf8(&mut buf));
    }

    fn emit_call_args(&mut self, args: &[CallArg]) {
        for (i, a) in args.iter().enumerate() {
            if i > 0 { self.emit(", "); }
            match a {
                CallArg::Positional(e) => self.emit_expr(e),
                CallArg::Named(n, e) => {
                    self.emit(&n.name);
                    self.emit(": ");
                    self.emit_expr(e);
                }
                CallArg::Spread(e, _) => {
                    self.emit_expr(e);
                }
            }
        }
    }

    fn emit_binop(&mut self, op: BinOp) {
        match op {
            BinOp::Add => self.emit("+"),
            BinOp::Sub => self.emit("-"),
            BinOp::Mul => self.emit("*"),
            BinOp::Div => self.emit("/"),
            BinOp::Rem => self.emit("%"),
            BinOp::Eq => self.emit("=="),
            BinOp::Ne => self.emit("!="),
            BinOp::Lt => self.emit("<"),
            BinOp::Le => self.emit("<="),
            BinOp::Gt => self.emit(">"),
            BinOp::Ge => self.emit(">="),
            BinOp::And => self.emit("&&"),
            BinOp::Or => self.emit("||"),
            BinOp::LogicalAnd => self.emit("&&"),
            BinOp::LogicalOr => self.emit("||"),
            BinOp::BitAnd => self.emit("&"),
            BinOp::BitOr => self.emit("|"),
            BinOp::BitXor => self.emit("^"),
            BinOp::Shl => self.emit("<<"),
            BinOp::Shr => self.emit(">>"),
            BinOp::Concat => self.emit("+"),
        }
    }
}

impl Default for Codegen {
    fn default() -> Self {
        Codegen::new()
    }
}

/// Return the precedence tier of a binary operator (higher binds tighter).
fn binop_precedence(op: BinOp) -> u8 {
    match op {
        BinOp::Mul | BinOp::Div | BinOp::Rem => 7,
        BinOp::Add | BinOp::Sub | BinOp::Concat => 6,
        BinOp::Shl | BinOp::Shr => 5,
        BinOp::BitAnd => 4,
        BinOp::BitOr | BinOp::BitXor => 3,
        BinOp::Eq | BinOp::Ne | BinOp::Lt | BinOp::Le | BinOp::Gt | BinOp::Ge => 2,
        BinOp::And | BinOp::Or | BinOp::LogicalAnd | BinOp::LogicalOr => 1,
    }
}

/// Analyze a function body and return the names that must be `mut` in generated Rust.
fn analyze_mutability(
    body: &Block,
    method_writes: &HashMap<(String, String), bool>,
    fn_returns_fn: &std::collections::HashSet<String>,
) -> (Vec<String>, HashMap<String, String>) {
    let mut muts = Vec::new();
    let mut var_types: HashMap<String, String> = HashMap::new();
    analyze_block(body, method_writes, fn_returns_fn, &mut var_types, &mut muts);
    (muts, var_types)
}

/// True when the value is a call to a known top-level fn that returns a function type.
fn fn_call_returns_fn(value: &Expr, fn_returns_fn: &std::collections::HashSet<String>) -> bool {
    if let Expr::Call(callee, _, _) = value {
        if let Expr::Ident(id) = callee.as_ref() {
            return fn_returns_fn.contains(&id.name);
        }
    }
    false
}

/// True when the annotation is a function type (`fn(P) -> R`).
fn is_fn_type(t: &Option<TypeAnnot>) -> bool {
    t.as_ref().is_some_and(|t| matches!(t.kind, TypeAnnotKind::Function(..)))
}

/// True when the closure references any name outside its own params and inner bindings.
fn closure_captures(params: &[Param], body: &Block) -> bool {
    let mut bound: Vec<String> = params.iter().map(|p| p.name.name.clone()).collect();
    collect_block_bindings(body, &mut bound);
    let mut referenced = Vec::new();
    collect_block_idents(body, &mut referenced);
    referenced.iter().any(|n| !bound.contains(n))
}

/// True when the closure assigns to a captured (non-param, non-inner) name.
fn closure_mutates_captures(params: &[Param], body: &Block) -> bool {
    let mut bound: Vec<String> = params.iter().map(|p| p.name.name.clone()).collect();
    collect_block_bindings(body, &mut bound);
    let mut assigned = Vec::new();
    collect_assign_targets(body, &mut assigned);
    assigned.iter().any(|n| !bound.contains(n))
}

/// Collect every identifier bound by let/var/for inside a block, recursively.
fn collect_block_bindings(block: &Block, out: &mut Vec<String>) {
    for stmt in &block.stmts {
        collect_stmt_bindings(stmt, out);
    }
}

/// Collect identifiers bound by one statement, recursively.
fn collect_stmt_bindings(stmt: &Stmt, out: &mut Vec<String>) {
    match stmt {
        Stmt::Let { name, .. } | Stmt::Var { name, .. } => {
            out.push(name.name.clone());
        }
        Stmt::For { var, .. } => out.push(var.name.clone()),
        Stmt::If { then_body, elseifs, else_body, .. } => {
            collect_block_bindings(then_body, out);
            for (_, b) in elseifs {
                collect_block_bindings(b, out);
            }
            if let Some(b) = else_body {
                collect_block_bindings(b, out);
            }
        }
        Stmt::While { body: b, .. } | Stmt::Repeat { body: b, .. } | Stmt::Loop { body: b, .. }
        | Stmt::Block(b, _) | Stmt::Unsafe(b, _) => collect_block_bindings(b, out),
        Stmt::Match { arms, .. } => {
            for arm in arms {
                collect_pattern_bindings(&arm.pattern, out);
                collect_block_bindings(&arm.body, out);
            }
        }
        _ => {}
    }
}

/// Collect names bound by a pattern.
fn collect_pattern_bindings(p: &Pattern, out: &mut Vec<String>) {
    match p {
        Pattern::Binding(id) => out.push(id.name.clone()),
        Pattern::EnumVariant { sub, .. } => {
            for s in sub {
                collect_pattern_bindings(s, out);
            }
        }
        Pattern::Struct { fields, .. } => {
            for (_, sub) in fields {
                collect_pattern_bindings(sub, out);
            }
        }
        Pattern::Tuple(elems, _) | Pattern::Array(elems, _) | Pattern::Or(elems, _) => {
            for e in elems {
                collect_pattern_bindings(e, out);
            }
        }
        Pattern::As(inner, id, _) => {
            out.push(id.name.clone());
            collect_pattern_bindings(inner, out);
        }
        _ => {}
    }
}

/// True when the value is a unary-negated integer literal (still an Int).
fn int_neg_literal(value: &Expr) -> bool {
    matches!(
        value,
        Expr::UnaryOp(UnaryOp::Neg, inner, _) if matches!(inner.as_ref(), Expr::IntLit(..))
    )
}

/// True when a const initializer makes the const usable as a count-loop bound.
fn int_const_value(value: &Expr) -> bool {
    matches!(value, Expr::IntLit(..)) || int_neg_literal(value)
}

/// Collect every plain identifier referenced anywhere in a block.
fn collect_block_idents(block: &Block, out: &mut Vec<String>) {
    for stmt in &block.stmts {
        collect_stmt_idents(stmt, out);
    }
    if let Some(tail) = &block.tail {
        collect_expr_idents(tail, out);
    }
}

/// Collect identifier references from one statement.
fn collect_stmt_idents(stmt: &Stmt, out: &mut Vec<String>) {
    match stmt {
        Stmt::Let { value, .. } | Stmt::Var { value, .. } => collect_expr_idents(value, out),
        Stmt::Assign { target, value, .. } => {
            collect_expr_idents(target, out);
            collect_expr_idents(value, out);
        }
        Stmt::Expr(e, _) => collect_expr_idents(e, out),
        Stmt::If { cond, then_body, elseifs, else_body, .. } => {
            collect_expr_idents(cond, out);
            collect_block_idents(then_body, out);
            for (c, b) in elseifs {
                collect_expr_idents(c, out);
                collect_block_idents(b, out);
            }
            if let Some(b) = else_body {
                collect_block_idents(b, out);
            }
        }
        Stmt::While { cond, body: b, .. } => {
            collect_expr_idents(cond, out);
            collect_block_idents(b, out);
        }
        Stmt::Repeat { body: b, cond, .. } => {
            collect_block_idents(b, out);
            collect_expr_idents(cond, out);
        }
        Stmt::For { var, iter, body, .. } => {
            out.push(var.name.clone());
            collect_expr_idents(iter, out);
            collect_block_idents(body, out);
        }
        Stmt::Loop { body, .. } => collect_block_idents(body, out),
        Stmt::Return(e, _) => {
            if let Some(e) = e {
                collect_expr_idents(e, out);
            }
        }
        Stmt::Match { scrutinee, arms, .. } => {
            collect_expr_idents(scrutinee, out);
            for arm in arms {
                collect_block_idents(&arm.body, out);
                if let Some(g) = &arm.guard {
                    collect_expr_idents(g, out);
                }
            }
        }
        Stmt::Block(b, _) | Stmt::Unsafe(b, _) => collect_block_idents(b, out),
        Stmt::Spawn { call, .. } => collect_expr_idents(call, out),
        _ => {}
    }
}

/// Collect identifier references from one expression, recursively.
fn collect_expr_idents(e: &Expr, out: &mut Vec<String>) {
    match e {
        Expr::Ident(id) => out.push(id.name.clone()),
        Expr::Assign(t, _, v, _) => {
            collect_expr_idents(t, out);
            collect_expr_idents(v, out);
        }
        Expr::MethodCall(recv, _, args, _, _) => {
            collect_expr_idents(recv, out);
            for a in args {
                if let Some(inner) = call_arg_expr(a) {
                    collect_expr_idents(inner, out);
                }
            }
        }
        Expr::Call(callee, args, _) => {
            collect_expr_idents(callee, out);
            for a in args {
                if let Some(inner) = call_arg_expr(a) {
                    collect_expr_idents(inner, out);
                }
            }
        }
        Expr::Closure(params, _, body, _) => {
            let mut inner: Vec<String> = Vec::new();
            for p in params {
                inner.push(p.name.name.clone());
            }
            collect_block_idents(body, &mut inner);
            out.extend(inner);
        }
        Expr::BinOp(l, _, r, _) => {
            collect_expr_idents(l, out);
            collect_expr_idents(r, out);
        }
        Expr::UnaryOp(_, i, _) => collect_expr_idents(i, out),
        Expr::Index(a, i, _) => {
            collect_expr_idents(a, out);
            collect_expr_idents(i, out);
        }
        Expr::Field(recv, _, _) | Expr::QuestionDot(recv, _, _) => collect_expr_idents(recv, out),
        Expr::IfExpr(c, t, ei, el, _) => {
            collect_expr_idents(c, out);
            collect_block_idents(t, out);
            for (c2, b) in ei {
                collect_expr_idents(c2, out);
                collect_block_idents(b, out);
            }
            if let Some(b) = el {
                collect_block_idents(b, out);
            }
        }
        Expr::MatchExpr(scrut, arms, _) => {
            collect_expr_idents(scrut, out);
            for arm in arms {
                collect_block_idents(&arm.body, out);
                if let Some(g) = &arm.guard {
                    collect_expr_idents(g, out);
                }
            }
        }
        Expr::BlockExpr(b, _) => collect_block_idents(b, out),
        Expr::InterpStr(parts, _) => {
            for p in parts {
                if let InterpStrPart::Expr(inner) = p {
                    collect_expr_idents(inner, out);
                }
            }
        }
        Expr::Array(elems, _) | Expr::Tuple(elems, _) => {
            for el in elems {
                collect_expr_idents(el, out);
            }
        }
        Expr::Map(fields, _) | Expr::StructLit(_, fields, _) => {
            for f in fields {
                collect_expr_idents(&f.value, out);
            }
        }
        Expr::PipeForward(l, r, _) | Expr::BackPipe(l, r, _) => {
            collect_expr_idents(l, out);
            collect_expr_idents(r, out);
        }
        Expr::Range(l, h, _, _) => {
            if let Some(l) = l {
                collect_expr_idents(l, out);
            }
            if let Some(h) = h {
                collect_expr_idents(h, out);
            }
        }
        _ => {}
    }
}

/// Collect the root identifiers of assignment targets in a block.
fn collect_assign_targets(block: &Block, out: &mut Vec<String>) {
    for stmt in &block.stmts {
        if let Stmt::Assign { target, .. } = stmt {
            collect_target_roots(target, out);
        }
        match stmt {
            Stmt::If { then_body, elseifs, else_body, .. } => {
                collect_assign_targets(then_body, out);
                for (_, b) in elseifs {
                    collect_assign_targets(b, out);
                }
                if let Some(b) = else_body {
                    collect_assign_targets(b, out);
                }
            }
            Stmt::While { body: b, .. } | Stmt::Repeat { body: b, .. } | Stmt::Loop { body: b, .. }
            | Stmt::Block(b, _) | Stmt::Unsafe(b, _) => collect_assign_targets(b, out),
            Stmt::Match { arms, .. } => {
                for arm in arms {
                    collect_assign_targets(&arm.body, out);
                }
            }
            Stmt::Expr(Expr::Assign(t, _, _, _), _) => collect_target_roots(t, out),
            _ => {}
        }
    }
}

/// Walk to the root identifier of an assignment target expression.
fn collect_target_roots(target: &Expr, out: &mut Vec<String>) {
    let mut cur = target;
    loop {
        match cur {
            Expr::Ident(id) => {
                out.push(id.name.clone());
                return;
            }
            Expr::Field(recv, _, _) | Expr::Index(recv, _, _) => cur = recv,
            _ => return,
        }
    }
}

/// Walk a block recording variable types and mutability requirements.
fn analyze_block(
    block: &Block,
    method_writes: &HashMap<(String, String), bool>,
    fn_returns_fn: &std::collections::HashSet<String>,
    var_types: &mut HashMap<String, String>,
    muts: &mut Vec<String>,
) {
    for stmt in &block.stmts {
        analyze_stmt(stmt, method_writes, fn_returns_fn, var_types, muts);
    }
    if let Some(tail) = &block.tail {
        analyze_expr(&tail, method_writes, fn_returns_fn, var_types, muts);
    }
}

/// Walk one statement for mutability effects.
fn analyze_stmt(
    stmt: &Stmt,
    method_writes: &HashMap<(String, String), bool>,
    fn_returns_fn: &std::collections::HashSet<String>,
    var_types: &mut HashMap<String, String>,
    muts: &mut Vec<String>,
) {
    match stmt {
        Stmt::Let { name, ty, value, .. } | Stmt::Var { name, ty, value, .. } => {
            analyze_expr(value, method_writes, fn_returns_fn, var_types, muts);
            if let Some(t) = ty {
                if let TypeAnnotKind::Named(id, _) = &t.kind {
                    var_types.insert(name.name.clone(), id.name.clone());
                }
            }
            if let Expr::StructLit(ty_name, _, _) = value {
                var_types.insert(name.name.clone(), ty_name.name.clone());
            }
            if let Expr::Array(..) = value {
                var_types.insert(name.name.clone(), "Vec".into());
            }
            if let Expr::Map(..) = value {
                var_types.insert(name.name.clone(), "Map".into());
            }
            if let Expr::IntLit(..) = value {
                var_types.insert(name.name.clone(), "Int".into());
            }
            if int_neg_literal(value) {
                var_types.insert(name.name.clone(), "Int".into());
            }
            if let Expr::Ident(src) = value {
                if let Some(t) = var_types.get(&src.name) {
                    var_types.insert(name.name.clone(), t.clone());
                }
            }
            let needs_mut = is_fn_type(ty)
                || fn_call_returns_fn(value, fn_returns_fn)
                || if let Expr::Closure(params, _, body, _) = value {
                    closure_mutates_captures(params, body)
                } else {
                    false
                };
            if needs_mut {
                push_unique(muts, name.name.clone());
            }
        }
        Stmt::Assign { target, value, .. } => {
            record_assign_target(target, var_types, muts);
            analyze_expr(value, method_writes, fn_returns_fn, var_types, muts);
        }
        Stmt::Expr(e, _) => analyze_expr(e, method_writes, fn_returns_fn, var_types, muts),
        Stmt::If { cond, then_body, elseifs, else_body, .. } => {
            analyze_expr(cond, method_writes, fn_returns_fn, var_types, muts);
            analyze_block(then_body, method_writes, fn_returns_fn, var_types, muts);
            for (c, b) in elseifs {
                analyze_expr(c, method_writes, fn_returns_fn, var_types, muts);
                analyze_block(b, method_writes, fn_returns_fn, var_types, muts);
            }
            if let Some(b) = else_body {
                analyze_block(b, method_writes, fn_returns_fn, var_types, muts);
            }
        }
        Stmt::While { cond, body, .. } => {
            analyze_expr(cond, method_writes, fn_returns_fn, var_types, muts);
            analyze_block(body, method_writes, fn_returns_fn, var_types, muts);
        }
        Stmt::Repeat { body, cond, .. } => {
            analyze_block(body, method_writes, fn_returns_fn, var_types, muts);
            analyze_expr(cond, method_writes, fn_returns_fn, var_types, muts);
        }
        Stmt::For { var, iter, body, .. } => {
            analyze_expr(iter, method_writes, fn_returns_fn, var_types, muts);
            analyze_block(body, method_writes, fn_returns_fn, var_types, muts);
            let _ = var;
        }
        Stmt::Loop { body, .. } => analyze_block(body, method_writes, fn_returns_fn, var_types, muts),
        Stmt::Return(e, _) => {
            if let Some(e) = e {
                analyze_expr(e, method_writes, fn_returns_fn, var_types, muts);
            }
        }
        Stmt::Match { scrutinee, arms, .. } => {
            analyze_expr(scrutinee, method_writes, fn_returns_fn, var_types, muts);
            for arm in arms {
                analyze_block(&arm.body, method_writes, fn_returns_fn, var_types, muts);
                if let Some(g) = &arm.guard {
                    analyze_expr(g, method_writes, fn_returns_fn, var_types, muts);
                }
            }
        }
        Stmt::Block(b, _) | Stmt::Unsafe(b, _) => {
            analyze_block(b, method_writes, fn_returns_fn, var_types, muts)
        }
        Stmt::Spawn { call, .. } => analyze_expr(call, method_writes, fn_returns_fn, var_types, muts),
        _ => {}
    }
}

/// Walk one expression for mutability effects.
fn analyze_expr(
    e: &Expr,
    method_writes: &HashMap<(String, String), bool>,
    fn_returns_fn: &std::collections::HashSet<String>,
    var_types: &mut HashMap<String, String>,
    muts: &mut Vec<String>,
) {
    match e {
        Expr::Assign(target, _, value, _) => {
            record_assign_target(target, var_types, muts);
            analyze_expr(value, method_writes, fn_returns_fn, var_types, muts);
        }
        Expr::MethodCall(recv, name, _, _, _) => {
            if let Expr::Ident(id) = recv.as_ref() {
                if let Some(ty) = var_types.get(&id.name) {
                    let key = (ty.clone(), name.name.clone());
                    if method_writes.get(&key).copied().unwrap_or(false) {
                        push_unique(muts, id.name.clone());
                    }
                }
            }
            analyze_expr(recv, method_writes, fn_returns_fn, var_types, muts);
        }
        Expr::Call(callee, args, _) => {
            analyze_expr(callee, method_writes, fn_returns_fn, var_types, muts);
            for a in args {
                if let Some(inner) = call_arg_expr(a) {
                    analyze_expr(inner, method_writes, fn_returns_fn, var_types, muts);
                }
            }
        }
        Expr::BinOp(l, _, r, _) => {
            analyze_expr(l, method_writes, fn_returns_fn, var_types, muts);
            analyze_expr(r, method_writes, fn_returns_fn, var_types, muts);
        }
        Expr::UnaryOp(_, inner, _) => analyze_expr(inner, method_writes, fn_returns_fn, var_types, muts),
        Expr::Closure(_, _, body, _) => {
            analyze_block(body, method_writes, fn_returns_fn, var_types, muts);
        }
        Expr::IfExpr(c, t, ei, el, _) => {
            analyze_expr(c, method_writes, fn_returns_fn, var_types, muts);
            analyze_block(t, method_writes, fn_returns_fn, var_types, muts);
            for (c2, b) in ei {
                analyze_expr(c2, method_writes, fn_returns_fn, var_types, muts);
                analyze_block(b, method_writes, fn_returns_fn, var_types, muts);
            }
            if let Some(b) = el {
                analyze_block(b, method_writes, fn_returns_fn, var_types, muts);
            }
        }
        Expr::MatchExpr(scrut, arms, _) => {
            analyze_expr(scrut, method_writes, fn_returns_fn, var_types, muts);
            for arm in arms {
                analyze_block(&arm.body, method_writes, fn_returns_fn, var_types, muts);
            }
        }
        Expr::BlockExpr(b, _) => analyze_block(b, method_writes, fn_returns_fn, var_types, muts),
        Expr::InterpStr(parts, _) => {
            for p in parts {
                if let InterpStrPart::Expr(inner) = p {
                    analyze_expr(inner, method_writes, fn_returns_fn, var_types, muts);
                }
            }
        }
        Expr::Array(elems, _) | Expr::Tuple(elems, _) => {
            for el in elems {
                analyze_expr(el, method_writes, fn_returns_fn, var_types, muts);
            }
        }
        Expr::Map(fields, _) | Expr::StructLit(_, fields, _) => {
            for f in fields {
                analyze_expr(&f.value, method_writes, fn_returns_fn, var_types, muts);
            }
        }
        _ => {}
    }
}

/// Mark the root binding of an assignment target as mutable.
fn record_assign_target(target: &Expr, _var_types: &mut HashMap<String, String>, muts: &mut Vec<String>) {
    let mut cur = target;
    loop {
        match cur {
            Expr::Ident(id) => {
                push_unique(muts, id.name.clone());
                return;
            }
            Expr::SelfExpr(_) => return,
            Expr::Field(recv, _, _) | Expr::Index(recv, _, _) => cur = recv,
            _ => return,
        }
    }
}

/// Extract the expression of a call argument.
fn call_arg_expr(a: &CallArg) -> Option<&Expr> {
    match a {
        CallArg::Positional(e) => Some(e),
        CallArg::Named(_, e) => Some(e),
        CallArg::Spread(e, _) => Some(e),
    }
}

/// Append a name to the mut list if it is not already present.
fn push_unique(muts: &mut Vec<String>, name: String) {
    if !muts.contains(&name) {
        muts.push(name);
    }
}

/// Convenience function: generate Rust code from a lowered HIR module.
pub fn generate(module: &HirModule) -> String {
    let mut cg = Codegen::new();
    cg.emit_module(module)
}

/// Convenience function: generate Rust code from a raw AST module (parses, lowers, then emits).
pub fn generate_ast(module: &crate::ast::Module) -> String {
    let hir_module = crate::hir::lower(module);
    generate(&hir_module)
}

/// Convenience function: lex, parse, lower, and codegen a source string in one step.
pub fn compile_to_rust(src: &str, file_id: u32) -> (String, crate::diag::Diagnostics) {
    let (module, mut diags) = crate::parser::parse(src, file_id);
    let hir_module = crate::hir::lower(&module);
    diags.extend(hir_module.diags.clone());
    let rust = generate(&hir_module);
    (rust, diags)
}
