/*
  Owner: PascalElixir / axolrs (GitHub org)
  Brief: Tutorial chapters for /learn derived from PROGRAMMINGLANGUAGEBIBLE sections.
*/

export interface LearnChapter {
  id: string;
  index: number;
  title: string;
  summary: string;
  level: 'Basics' | 'Intermediate' | 'Advanced' | 'Expert';
  estimatedMin: number;
  anchor: string;
}

export interface LearnSection {
  id: string;
  title: string;
  blurb: string;
  chapters: LearnChapter[];
}

export const learnSections: LearnSection[] = [
  {
    id: 'getting-started',
    title: 'Getting started',
    blurb: 'From zero to a running native binary. The minimum surface you need to write a real Axolotl program.',
    chapters: [
      {
        id: 'hello-world',
        index: 1,
        title: 'Hello World',
        summary: 'Print a line, exit, ship a native binary. Confirms bucket + axolc are wired.',
        level: 'Basics',
        estimatedMin: 5,
        anchor: '1-hello-world',
      },
      {
        id: 'comments',
        index: 2,
        title: 'Comments',
        summary: 'Lua-style `--` and `--[[ ]]` block comments. Zero runtime cost.',
        level: 'Basics',
        estimatedMin: 3,
        anchor: '2-comments',
      },
      {
        id: 'modules-use',
        index: 3,
        title: 'Modules and `use`',
        summary: 'One import syntax for local modules, local Rust, and external Cargo crates.',
        level: 'Basics',
        estimatedMin: 8,
        anchor: '3-modules-and-use',
      },
      {
        id: 'variables',
        index: 4,
        title: 'Variables (`let` and `var`)',
        summary: '`let` is immutable by default. `var` is opt-in mutability. No `mut` keyword.',
        level: 'Basics',
        estimatedMin: 8,
        anchor: '4-variables-let-and-var',
      },
    ],
  },
  {
    id: 'types-and-values',
    title: 'Types and values',
    blurb: 'The primitive and compound types, the type system, and the annotations you actually write.',
    chapters: [
      {
        id: 'primitives',
        index: 5,
        title: 'Primitive Types',
        summary: 'Int, UInt, Float, Bool, String, Char, Byte - and how they map to Rust.',
        level: 'Basics',
        estimatedMin: 10,
        anchor: '5-primitive-types',
      },
      {
        id: 'sized-types',
        index: 6,
        title: 'Sized Integer / Float Types',
        summary: 'i8..i64, u8..u64, f32, f64 - explicit widths when you need them.',
        level: 'Basics',
        estimatedMin: 7,
        anchor: '6-sized-integer-float-types',
      },
      {
        id: 'booleans',
        index: 7,
        title: 'Booleans',
        summary: 'true / false, truthiness, short-circuit.',
        level: 'Basics',
        estimatedMin: 4,
        anchor: '7-booleans',
      },
      {
        id: 'strings',
        index: 8,
        title: 'Strings',
        summary: 'UTF-8 String, slices, raw bytes, and the `---` doc-comment tag.',
        level: 'Basics',
        estimatedMin: 10,
        anchor: '8-strings',
      },
      {
        id: 'type-inference',
        index: 9,
        title: 'Type Inference',
        summary: 'The compiler infers almost everything. You annotate when it matters.',
        level: 'Basics',
        estimatedMin: 7,
        anchor: '9-type-inference',
      },
      {
        id: 'type-annotations',
        index: 10,
        title: 'Type Annotations',
        summary: 'Where to write them, where not to, and what `:` means in each context.',
        level: 'Basics',
        estimatedMin: 6,
        anchor: '10-type-annotations',
      },
      {
        id: 'nullable-types',
        index: 11,
        title: 'Nullable Types (`T?` and `null`)',
        summary: 'Optionality without Option, and how it lowers to Rust `Option<T>`.',
        level: 'Intermediate',
        estimatedMin: 10,
        anchor: '11-nullable-types-t-and-null',
      },
    ],
  },
  {
    id: 'functions-and-control-flow',
    title: 'Functions and control flow',
    blurb: 'Functions, closures, the four loop forms, and the Lua-style block endings.',
    chapters: [
      {
        id: 'print',
        index: 12,
        title: 'Print',
        summary: '`print` and `eprint` with format strings. Maps to `println!` and `eprintln!`.',
        level: 'Basics',
        estimatedMin: 5,
        anchor: '12-print',
      },
      {
        id: 'functions',
        index: 13,
        title: 'Functions',
        summary: '`fn name(args) ... end` - multiple returns, named args, defaults.',
        level: 'Basics',
        estimatedMin: 12,
        anchor: '13-functions',
      },
      {
        id: 'multiple-returns',
        index: 14,
        title: 'Multiple Return Values',
        summary: 'Return more than one thing. Tuple lowering is transparent.',
        level: 'Intermediate',
        estimatedMin: 6,
        anchor: '14-multiple-return-values',
      },
      {
        id: 'closures',
        index: 15,
        title: 'Closures',
        summary: 'Lambdas, captures, and how the borrow checker reasons about them.',
        level: 'Intermediate',
        estimatedMin: 12,
        anchor: '15-closures',
      },
      {
        id: 'if-elseif-else-end',
        index: 25,
        title: '`if / elseif / else / end`',
        summary: 'Lua-style block endings. No braces, no `then` outside the condition.',
        level: 'Basics',
        estimatedMin: 6,
        anchor: '25-if-elseif-else-end',
      },
      {
        id: 'while-do-end',
        index: 26,
        title: '`while / do / end`',
        summary: 'Loop with a condition. `break` and `continue` work as you expect.',
        level: 'Basics',
        estimatedMin: 5,
        anchor: '26-while-do-end',
      },
      {
        id: 'repeat-until',
        index: 27,
        title: '`repeat / until`',
        summary: 'Post-test loop from Lua. The condition sees variables from the body.',
        level: 'Basics',
        estimatedMin: 5,
        anchor: '27-repeat-until',
      },
      {
        id: 'for',
        index: 28,
        title: '`for` - Numeric and Iterator',
        summary: 'Numeric `for i = 1, 10 do ... end` and iterator `for x in xs do ... end`.',
        level: 'Basics',
        estimatedMin: 10,
        anchor: '28-for-numeric-and-iterator',
      },
      {
        id: 'break-continue',
        index: 29,
        title: '`break` / `continue`',
        summary: 'Loop control. Also `break N` for multi-level breaks.',
        level: 'Basics',
        estimatedMin: 5,
        anchor: '29-break-continue',
      },
    ],
  },
  {
    id: 'data-and-patterns',
    title: 'Data and patterns',
    blurb: 'Structs, tables, enums, interfaces, and the four match-replacement features.',
    chapters: [
      {
        id: 'structs',
        index: 16,
        title: 'Structs',
        summary: 'Named record types with `@derive`, `@repr`, and field shorthand.',
        level: 'Intermediate',
        estimatedMin: 12,
        anchor: '16-structs',
      },
      {
        id: 'methods',
        index: 17,
        title: 'Methods (no `impl` keyword)',
        summary: 'Methods live next to the struct. `:` is the method call.',
        level: 'Intermediate',
        estimatedMin: 8,
        anchor: '17-methods-no-impl-keyword',
      },
      {
        id: 'tables',
        index: 18,
        title: 'Tables and Record Literals',
        summary: 'Lua-style tables lowered to typed Rust records when the type is known.',
        level: 'Intermediate',
        estimatedMin: 12,
        anchor: '18-tables-and-record-literals',
      },
      {
        id: 'enums',
        index: 19,
        title: 'Enums',
        summary: 'Algebraic data types. Payloads, `@derive`, and exhaustive matching.',
        level: 'Intermediate',
        estimatedMin: 12,
        anchor: '19-enums',
      },
      {
        id: 'pattern-matching',
        index: 20,
        title: 'Pattern Matching',
        summary: 'Full match, guards, bindings, and what the compiler rejects.',
        level: 'Intermediate',
        estimatedMin: 14,
        anchor: '20-pattern-matching',
      },
      {
        id: 'interfaces',
        index: 21,
        title: 'Interfaces (Traits)',
        summary: 'Axolotl interfaces are Rust traits. Same dispatch rules, same cost.',
        level: 'Intermediate',
        estimatedMin: 14,
        anchor: '21-interfaces-traits',
      },
      {
        id: 'impl-blocks',
        index: 22,
        title: 'Implementation Blocks',
        summary: 'How methods get attached to types. Generic impls and trait impls.',
        level: 'Intermediate',
        estimatedMin: 10,
        anchor: '22-implementation-blocks',
      },
      {
        id: 'generics',
        index: 23,
        title: 'Generics',
        summary: 'Parametric polymorphism with bounds, associated types, and const generics.',
        level: 'Advanced',
        estimatedMin: 16,
        anchor: '23-generics',
      },
      {
        id: 'constants',
        index: 24,
        title: 'Constants and Compile-Time Evaluation',
        summary: '`const` and `comptime` - what runs at compile time and what does not.',
        level: 'Advanced',
        estimatedMin: 10,
        anchor: '24-constants-and-compile-time-evaluation',
      },
    ],
  },
  {
    id: 'collections-iter-ownership',
    title: 'Collections, iterators, ownership',
    blurb: 'The data structures you reach for and the ownership model that powers them.',
    chapters: [
      {
        id: 'arrays',
        index: 30,
        title: 'Arrays',
        summary: 'Fixed-size arrays and `Vec<T>`. Slice syntax and bounds checking.',
        level: 'Basics',
        estimatedMin: 10,
        anchor: '30-arrays',
      },
      {
        id: 'maps',
        index: 31,
        title: 'Maps',
        summary: '`HashMap` and `BTreeMap`. Lua-table sugar when the type is known.',
        level: 'Intermediate',
        estimatedMin: 10,
        anchor: '31-maps',
      },
      {
        id: 'iterators',
        index: 32,
        title: 'Iterators',
        summary: 'Zero-cost iterator chains. The same `Iterator` trait as Rust.',
        level: 'Intermediate',
        estimatedMin: 12,
        anchor: '32-iterators',
      },
      {
        id: 'ownership-inferred',
        index: 33,
        title: 'Ownership (Inferred)',
        summary: 'You almost never write a lifetime. The compiler figures it out.',
        level: 'Advanced',
        estimatedMin: 14,
        anchor: '33-ownership-inferred',
      },
      {
        id: 'explicit-ownership',
        index: 34,
        title: 'Explicit Ownership (`borrow`, `mut`, `move`)',
        summary: 'When you need to spell it out. Same semantics as Rust, smaller surface.',
        level: 'Advanced',
        estimatedMin: 14,
        anchor: '34-explicit-ownership-borrow-mut-move',
      },
      {
        id: 'references-borrows',
        index: 35,
        title: 'References and Borrows',
        summary: '`&T`, `&mut T`, and the rules the compiler enforces for you.',
        level: 'Advanced',
        estimatedMin: 12,
        anchor: '35-references-and-borrows',
      },
      {
        id: 'lifetimes',
        index: 36,
        title: 'Lifetimes (Inferred, Never Written)',
        summary: 'You never write a lifetime in Axolotl. They exist; they are not syntax.',
        level: 'Advanced',
        estimatedMin: 10,
        anchor: '36-lifetimes-inferred-never-written',
      },
    ],
  },
  {
    id: 'errors-and-concurrency',
    title: 'Errors and concurrency',
    blurb: 'Result/Option ergonomics, async/await, threads, channels, and Send/Sync.',
    chapters: [
      {
        id: 'result-error-handling',
        index: 37,
        title: 'Result and Error Handling (`!`, `?`, `??`, `try`/`catch`)',
        summary: 'The four error operators and what they lower to in Rust.',
        level: 'Intermediate',
        estimatedMin: 14,
        anchor: '37-result-and-error-handling-trycatch',
      },
      {
        id: 'option-chaining',
        index: 38,
        title: 'Option / Nullable Chaining (`?.` and `!.`)',
        summary: 'Optional access, unwrap-or-panic, and the lowering to `Option::map`.',
        level: 'Intermediate',
        estimatedMin: 10,
        anchor: '38-option-nullable-chaining-and',
      },
      {
        id: 'coroutines-tasks',
        index: 39,
        title: 'Coroutines and Tasks',
        summary: 'Lightweight tasks on the Tokio runtime, identical to Rust async.',
        level: 'Advanced',
        estimatedMin: 12,
        anchor: '39-coroutines-and-tasks',
      },
      {
        id: 'spawn-threads',
        index: 40,
        title: '`spawn` and Threads',
        summary: 'OS threads via `std::thread`. Send bounds inferred.',
        level: 'Advanced',
        estimatedMin: 10,
        anchor: '40-spawn-and-threads',
      },
      {
        id: 'channels',
        index: 41,
        title: 'Channels',
        summary: 'MPSC, SPSC, broadcast - same as `std::sync::mpsc` and `tokio::sync`.',
        level: 'Advanced',
        estimatedMin: 12,
        anchor: '41-channels',
      },
      {
        id: 'async-await',
        index: 42,
        title: '`async` / `await`',
        summary: 'The same async/await as Rust. Same runtime, same cost, same model.',
        level: 'Advanced',
        estimatedMin: 14,
        anchor: '42-async-await',
      },
      {
        id: 'send-sync',
        index: 43,
        title: 'Send / Sync (Inferred)',
        summary: 'You almost never write Send + Sync bounds. The compiler adds them.',
        level: 'Advanced',
        estimatedMin: 8,
        anchor: '43-send-sync-inferred',
      },
    ],
  },
  {
    id: 'unsafe-ffi-low-level',
    title: 'Unsafe, FFI, low-level',
    blurb: 'When you have to drop to the metal: unsafe, raw pointers, cblock, cppblock, rblock.',
    chapters: [
      {
        id: 'unsafe',
        index: 44,
        title: 'Unsafe',
        summary: 'The same `unsafe` as Rust. Same rules, same obligations.',
        level: 'Expert',
        estimatedMin: 10,
        anchor: '44-unsafe',
      },
      {
        id: 'raw-pointers',
        index: 45,
        title: 'Raw Pointers',
        summary: '`*mut T`, `*const T`. The escape hatch when you really need it.',
        level: 'Expert',
        estimatedMin: 10,
        anchor: '45-raw-pointers',
      },
      {
        id: 'memory-layout',
        index: 46,
        title: 'Memory Layout (`@repr(C)` etc.)',
        summary: 'Attribute-driven layout control for FFI and binary formats.',
        level: 'Expert',
        estimatedMin: 8,
        anchor: '46-memory-layout-reprc-etc',
      },
      {
        id: 'allocation-domains',
        index: 47,
        title: 'Allocation Domains (Stack / Heap / Arena / Persistent)',
        summary: 'Where your values live. The compiler picks; you can override.',
        level: 'Expert',
        estimatedMin: 12,
        anchor: '47-allocation-domains-stack-heap-arena-persistent',
      },
      {
        id: 'raii',
        index: 48,
        title: 'RAII and Deterministic Destruction',
        summary: 'Drop is real. There is no GC. Order is well-defined.',
        level: 'Expert',
        estimatedMin: 8,
        anchor: '48-raii-and-deterministic-destruction',
      },
      {
        id: 'ffi-cblock',
        index: 49,
        title: 'FFI: `cblock`',
        summary: 'Inline C blocks. Linked only if used. Zero overhead for unused.',
        level: 'Expert',
        estimatedMin: 12,
        anchor: '49-ffi-cblock',
      },
      {
        id: 'ffi-cppblock',
        index: 50,
        title: 'FFI: `cppblock`',
        summary: 'Inline C++ blocks with name mangling handled for you.',
        level: 'Expert',
        estimatedMin: 10,
        anchor: '50-ffi-cppblock',
      },
      {
        id: 'ffi-rblock',
        index: 51,
        title: 'FFI: `rblock`',
        summary: 'Inline Rust blocks for when you need a feature Axolotl does not surface.',
        level: 'Expert',
        estimatedMin: 8,
        anchor: '51-ffi-rblock',
      },
      {
        id: 'ffi-pyblock',
        index: 52,
        title: 'FFI: `pyblock`',
        summary: 'Inline Python via PyO3 for scripting and glue workloads.',
        level: 'Expert',
        estimatedMin: 8,
        anchor: '52-ffi-pyblock',
      },
      {
        id: 'extern-fn',
        index: 53,
        title: '`extern fn` (C Declarations)',
        summary: 'Declare external C symbols without writing a cblock.',
        level: 'Expert',
        estimatedMin: 6,
        anchor: '53-extern-fn-c-declarations',
      },
    ],
  },
  {
    id: 'metaprogramming',
    title: 'Metaprogramming and the smart compiler',
    blurb: 'Attributes, macros, reflection, source maps, and the smart compiler itself.',
    chapters: [
      {
        id: 'attributes',
        index: 54,
        title: 'Attributes (`@derive`, `@repr`, `@inline`, ...)',
        summary: 'The unified attribute syntax. Compiles to Rust attributes 1:1.',
        level: 'Advanced',
        estimatedMin: 10,
        anchor: '54-attributes-derive-repr-inline-etc',
      },
      {
        id: 'macros',
        index: 55,
        title: 'Macros and Procedural Macros',
        summary: 'Declarative and procedural macros. Same power as Rust macros.',
        level: 'Expert',
        estimatedMin: 14,
        anchor: '55-macros-and-procedural-macros',
      },
      {
        id: 'reflection',
        index: 56,
        title: 'Compile-Time Reflection (`@reflect`)',
        summary: 'Inspect types at compile time and generate code from the inspection.',
        level: 'Expert',
        estimatedMin: 12,
        anchor: '56-compile-time-reflection-reflect',
      },
      {
        id: 'parser-recovery',
        index: 57,
        title: 'Error Recovery in the Parser',
        summary: 'How the parser continues after an error to report more diagnostics.',
        level: 'Expert',
        estimatedMin: 8,
        anchor: '57-error-recovery-in-the-parser',
      },
      {
        id: 'source-maps',
        index: 58,
        title: 'Source Maps and Span Mapping',
        summary: 'Spans from Axolotl source to generated Rust for diagnostics.',
        level: 'Expert',
        estimatedMin: 8,
        anchor: '58-source-maps-and-span-mapping',
      },
      {
        id: 'mixed-projects',
        index: 59,
        title: 'Mixed `.axol` + `.rs` Projects',
        summary: 'Rust files live alongside Axolotl files. Both can call each other.',
        level: 'Advanced',
        estimatedMin: 10,
        anchor: '59-mixed-axol-rs-projects',
      },
      {
        id: 'emit-rust',
        index: 60,
        title: '`bucket emit-rust` (Inspect Generated Rust)',
        summary: 'See what the compiler produces. The output is idiomatic Rust.',
        level: 'Intermediate',
        estimatedMin: 6,
        anchor: '60-bucket-emit-rust-inspect-generated-rust',
      },
      {
        id: 'smart-compiler',
        index: 61,
        title: 'The Smart Compiler (Gills / Neoten / Regrow)',
        summary: 'The parts of axolc that reason about ownership, suggest fixes, and map spans.',
        level: 'Expert',
        estimatedMin: 14,
        anchor: '61-the-smart-compiler-gills-neoten-regrow',
      },
    ],
  },
  {
    id: 'toolchain-ecosystem',
    title: 'Toolchain and ecosystem',
    blurb: 'Bucket, the pond cache, the manifest, the lockfile, and the no-runtime invariant.',
    chapters: [
      {
        id: 'pond-cache',
        index: 62,
        title: 'The Pond Cache',
        summary: 'pnpm-style global cache at `~/.bucket/pond/`, project-local `pond/`.',
        level: 'Intermediate',
        estimatedMin: 8,
        anchor: '62-the-pond-cache',
      },
      {
        id: 'bucket-cli',
        index: 63,
        title: 'The Bucket CLI',
        summary: '`bucket new`, `bucket add`, `bucket run`, `bucket build`, `bucket emit-rust`.',
        level: 'Basics',
        estimatedMin: 10,
        anchor: '63-the-bucket-cli',
      },
      {
        id: 'bucket-jsonc',
        index: 64,
        title: 'Bucket.jsonc Manifest',
        summary: 'JSONC, not TOML. Comments allowed. Schema enforced.',
        level: 'Intermediate',
        estimatedMin: 10,
        anchor: '64-bucketjsonc-manifest',
      },
      {
        id: 'bucket-lock',
        index: 65,
        title: 'Bucket.lock Lockfile',
        summary: 'Reproducible builds. Locked Cargo dependencies.',
        level: 'Intermediate',
        estimatedMin: 6,
        anchor: '65-bucketlock-lockfile',
      },
      {
        id: 'foreign-crates',
        index: 66,
        title: 'Foreign Crates Just Work',
        summary: 'Every Cargo crate is an Axolotl crate on day one. No wrapping required.',
        level: 'Intermediate',
        estimatedMin: 8,
        anchor: '66-foreign-crates-just-work',
      },
      {
        id: 'real-rust-types',
        index: 67,
        title: 'The "Use the Real Rust Types" Rule',
        summary: "No Axolotl-flavored `Vec`. You import Rust's `Vec`. Always.",
        level: 'Intermediate',
        estimatedMin: 6,
        anchor: '67-the-use-the-real-rust-types-rule',
      },
      {
        id: 'no-runtime',
        index: 68,
        title: 'The "No Runtime" Invariant',
        summary: 'No VM. No GC. No interpreter. No scheduler. No object system.',
        level: 'Intermediate',
        estimatedMin: 8,
        anchor: '68-the-no-runtime-invariant',
      },
      {
        id: 'what-you-dont-use',
        index: 69,
        title: `The "What You Don't Use Doesn't Exist" Principle`,
        summary: 'No cblock? No C build machinery. No async? No Tokio. Ever.',
        level: 'Intermediate',
        estimatedMin: 6,
        anchor: '69-the-what-you-dont-use-doesnt-exist-principle',
      },
      {
        id: 'zero-overhead',
        index: 70,
        title: 'The Zero-Overhead Promise',
        summary: 'Axolotl vs. hand-written Rust: same binary, same cost, every time.',
        level: 'Intermediate',
        estimatedMin: 6,
        anchor: '70-the-zero-overhead-promise',
      },
    ],
  },
  {
    id: 'ergonomics',
    title: 'The high-level surface',
    blurb: 'The "less code than match" toolkit: case, pipes, named args, comprehensions, and friends.',
    chapters: [
      {
        id: 'match-replacements',
        index: 71,
        title: 'Match Replacements (the toolkit)',
        summary: 'Why match is not the only way. Four alternatives, four contexts.',
        level: 'Intermediate',
        estimatedMin: 10,
        anchor: '71-match-replacements-the-less-code-than-match-toolkit',
      },
      {
        id: 'case-syntax',
        index: 72,
        title: '`case` Syntax (Terse Match)',
        summary: 'The short form of match for the common case of value dispatch.',
        level: 'Intermediate',
        estimatedMin: 8,
        anchor: '72-case-syntax-terse-match',
      },
      {
        id: 'variant-handlers',
        index: 73,
        title: 'Variant-Handler Methods (Match as Dispatch)',
        summary: 'Methods on enum variants. Match becomes a method call.',
        level: 'Advanced',
        estimatedMin: 10,
        anchor: '73-variant-handler-methods-match-as-dispatch',
      },
      {
        id: 'dispatch-tables',
        index: 74,
        title: 'Dispatch Tables (Lua-Style, Statically Checked)',
        summary: 'Lua-style dispatch tables with compile-time exhaustiveness.',
        level: 'Advanced',
        estimatedMin: 12,
        anchor: '74-dispatch-tables-lua-style-statically-checked',
      },
      {
        id: 'let-else',
        index: 75,
        title: '`let-else` (Early Return Patterns)',
        summary: 'Bind-or-return in one line. Same lowering as Rust.',
        level: 'Intermediate',
        estimatedMin: 6,
        anchor: '75-let-else-early-return-patterns',
      },
      {
        id: 'pipe',
        index: 76,
        title: 'Pipe `|>` and Reverse Application `<|`',
        summary: 'Elixir/F#-style pipes. Compiles to nested function calls.',
        level: 'Intermediate',
        estimatedMin: 8,
        anchor: '76-pipe-and-reverse-application',
      },
      {
        id: 'named-args',
        index: 77,
        title: 'Named Arguments',
        summary: 'Call functions with `name = value`. Lowers to a struct + impl.',
        level: 'Intermediate',
        estimatedMin: 8,
        anchor: '77-named-arguments',
      },
      {
        id: 'default-params',
        index: 78,
        title: 'Default Parameter Values',
        summary: 'Optional args with defaults. No overloads, no builders needed.',
        level: 'Intermediate',
        estimatedMin: 6,
        anchor: '78-default-parameter-values',
      },
      {
        id: 'spread',
        index: 79,
        title: 'Spread Operator (`...`)',
        summary: 'Spread arrays into args, struct literals, and other arrays.',
        level: 'Intermediate',
        estimatedMin: 6,
        anchor: '79-spread-operator',
      },
      {
        id: 'destructuring',
        index: 80,
        title: 'Destructuring Assignment',
        summary: 'Tuple, struct, and enum destructuring in one `let`.',
        level: 'Intermediate',
        estimatedMin: 8,
        anchor: '80-destructuring-assignment',
      },
      {
        id: 'if-let-chains',
        index: 81,
        title: 'If-Let Chains',
        summary: 'Multiple `if let` bindings in one condition. Same as Rust.',
        level: 'Intermediate',
        estimatedMin: 8,
        anchor: '81-if-let-chains',
      },
      {
        id: 'comprehensions',
        index: 82,
        title: 'List / Map / Set Comprehensions',
        summary: 'Python-style comprehensions that lower to `iter().map().collect()`.',
        level: 'Intermediate',
        estimatedMin: 12,
        anchor: '82-list-map-set-comprehensions',
      },
      {
        id: 'method-cascading',
        index: 83,
        title: 'Method Cascading',
        summary: 'Dart-style `..` cascade. Build up a value in one expression.',
        level: 'Intermediate',
        estimatedMin: 6,
        anchor: '83-method-cascading',
      },
      {
        id: 'multi-line-strings',
        index: 84,
        title: 'Multi-line / Raw / Tagged Strings',
        summary: 'Heredocs, raw strings, and tag-prefixed strings for interpolation.',
        level: 'Intermediate',
        estimatedMin: 8,
        anchor: '84-multi-line-raw-tagged-strings',
      },
      {
        id: 'number-suffix-literals',
        index: 85,
        title: 'Number-Suffix Literals (`4_KB`, `16_ms`, ...)',
        summary: 'Typed numeric literals with units. Compile-time checked.',
        level: 'Intermediate',
        estimatedMin: 6,
        anchor: '85-number-suffix-literals-4_kb-16_ms',
      },
      {
        id: 'doc-comments',
        index: 86,
        title: 'Documentation Comments (`---`)',
        summary: 'Triple-dash doc comments compile to Rust doc comments.',
        level: 'Basics',
        estimatedMin: 5,
        anchor: '86-documentation-comments',
      },
      {
        id: 'inline-tests',
        index: 87,
        title: 'Inline Tests and Examples',
        summary: 'Code blocks in doc comments run as tests. Like Rust doctests.',
        level: 'Intermediate',
        estimatedMin: 6,
        anchor: '87-inline-tests-and-examples',
      },
      {
        id: 'auto-derive',
        index: 88,
        title: 'Auto-Derive Common Traits',
        summary: 'Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize - auto.',
        level: 'Intermediate',
        estimatedMin: 6,
        anchor: '88-auto-derive-common-traits',
      },
      {
        id: 'quick-constructors',
        index: 89,
        title: 'Quick Constructors (`Type:new`)',
        summary: 'Zero-arg `Type:new` and field-default constructors.',
        level: 'Basics',
        estimatedMin: 5,
        anchor: '89-quick-constructors-typenew',
      },
      {
        id: 'struct-update',
        index: 90,
        title: 'Struct Update Syntax',
        summary: "Rust's `..base` syntax for partial updates.",
        level: 'Intermediate',
        estimatedMin: 5,
        anchor: '90-struct-update-syntax',
      },
      {
        id: 'ergonomic-surface-summary',
        index: 91,
        title: 'The High-Level Surface Summary',
        summary: 'The whole enjoyable layer on one page. Sugar, not a separate mode.',
        level: 'Intermediate',
        estimatedMin: 10,
        anchor: '91-the-high-level-surface-summary',
      },
    ],
  },
];

export function totalChapters(): number {
  return learnSections.reduce((n, s) => n + s.chapters.length, 0);
}
